kind = "web"
previewPath = "/"
title = "Meu Site"
version = "1.0.0"
id = "artifacts/meu-site"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22554

[services.development]
run = "pnpm --filter @workspace/meu-site run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/meu-site", "run", "build" ]
publicDir = "artifacts/meu-site/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22554"
BASE_PATH = "/"
